### ISSUE TITLE
Getting mixed limbs

### ISSUE THREAD

**Issue by LuongPhuHoa** [Delcos/Hentai-Diffusion#18]
I tried to generate some NSFW image but it got some with mixed limbs, I had added negative prompt but it didn't work.

[Here are the prompts](https://anotepad.com/notes/fpcwysea)

[Here are the images](https://imgur.com/a/iQNKSuQ)

**Comment by Kuroseji** [comment]
I have noticed that issue also at the 768x768 resolution. It's possible that is an issue with Stable Diffusion in general being trained on 512x512 but This might have been trained with a different resolution. A temporary solution might be using a lower resolution.

**Comment by LuongPhuHoa** [comment]
> 

I have tried in 512x512 but still get the same result, and 90% of the images are censored like ecchi anime, 5% left like the nipples and other sensitive parts are disappeared

**Comment by Kuroseji** [comment]
Well for 1 you have censored and mosaic_censoring in your prompt and negative prompt.  I assume the main prompt takes precedence in generations which is why you are seeing censorship still. The missing sensitive parts might also be due to the negative prompt removing "bad/poorly drawn" sensitive parts. You can try running with no negative prompt and then just add terms to the negative prompt as you notice issues. More or less sampling steps might also help. I tried running your prompt at 768x768 and the results were mostly fine. Also as a side note, your prompt was a bit too long for my ui so the prompt after "puckered" was cut off so most of mine are missing the more suggestive parts.

Steps: 30, Sampler: k_euler_a, CFG scale: 9.0, Seed: 332250147
[My results](https://imgur.com/a/gnMIOgN)

**Comment by LuongPhuHoa** [comment]
I also had problems with generating images with 2+ people, it cannot do actions like hug, hold hands, or bent over. Their limbs always got collapse or duplicate

**Comment by Kuroseji** [comment]
Not sure what to tell you about that. I'm not seeing those issues. Have you tried rearranging your prompts? It usually helps to put the most important things near the front of the prompt.

**Comment by LuongPhuHoa** [comment]
I met this [errors](https://imgur.com/a/UWAlSBf)

**Comment by LuongPhuHoa** [comment]
I just realized this. When I used 512x512 image size, the generated image sometimes gets cropped like [this](https://imgur.com/a/uHLRLd5). But when I changed to the larger size, I met all those errors I mentioned above

**Comment by Kuroseji** [comment]
That's not surprising, the cropping thing is pretty common with Stable Diffusion in general.  If you haven't already you can try adding "cropped" to the negative prompt or you can try changing the aspect ratio of the generations to be portrait or wide to better reflect your desired output. 
I believe most models are trained at 512x512 so that explains why fewer issues show up when you generate using that resolution.

**Comment by LuongPhuHoa** [comment]
I can use 512x512 for now, but is there any way to get more detailed body parts? Like n*pple,*ss or b**bs.

**Comment by Kuroseji** [comment]
In theory you could try generating just thing you want to be in high detail by itself and then use image editing software to replace the less detailed parts. Terms like "highly detailed" might also help(I haven't done extensive testing on this) or you can try using img2img with masking but I can't give you too many tips on img2img, I'm still trying to figure out a good process for that one myself.

**Comment by LuongPhuHoa** [comment]
I also think the generated images are gloomy. Is there any way to make them bright? I had tried to add prompts like "contrast, vibrant" but it didn't help

**Comment by zipper11** [comment]
> I met this [errors](https://imgur.com/a/UWAlSBf)

how do you even get this high resolution results. Mine are very low. I've tried getting the same [results](https://imgur.com/a/gnMIOgN) as you with the seed / input but I keep getting different results

**Comment by LuongPhuHoa** [comment]
> > I met this [errors](https://imgur.com/a/UWAlSBf)
> 
> how do you even get this high resolution results. Mine are very low. I've tried getting the same [results](https://imgur.com/a/gnMIOgN) as you with the seed / input but I keep getting different results

try to add "highres, absurdres" to the prompt

**Comment by zipper11** [comment]
> 

I tried, not much improvement. Even if I try exactly the same promt you added in the first post I get different results :(

**Comment by LuongPhuHoa** [comment]
> > 
> 
> I tried, not much improvement. Even if I try exactly the same promt you added in the first post I get different results :(


I used this setting :v try
Steps: 150, Sampler: Euler a, CFG scale: 20

**Comment by Kuroseji** [comment]
> I also think the generated images are gloomy. Is there any way to make them bright? I had tried to add prompts like "contrast, vibrant" but it didn't help

You can try adding terms like "happy, bright, joy" Those should adjust the "mood" of an image.

**Comment by Kuroseji** [comment]
> > 
> 
> I tried, not much improvement. Even if I try exactly the same promt you added in the first post I get different results :(

Just FYI those were done at 768x768 resolution. I think the default for most tools is 512x512. Not sure if you were talking actual resolution or perceived resolution as @LuongPhuHoa was describing.

**Comment by zipper11** [comment]
@Kuroseji is k_euler_a just the default Euler a? I'm using the latest Stable Diffusion and HD-17. Getting different results weird with the readme negative propt / negative promt of @LuongPhuHoa

**Comment by Kuroseji** [comment]
k_euler_a should be the default  Euler a, my ui is isn't the automatic one most people use. Good catch on the negative prompt, I don't use the readme negative prompt. It had a lot of duplicate terms and things I didn't necessarily want excluded so I built my own.

My UI doesn't save the negative prompts with the positive one but I think this is the correct one

"bad anatomy, blurry, disfigured, poorly drawn face, mutation, mutated, poorly drawn hands, extra_limb*, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, artist name"
