### ISSUE TITLE
error starting up

### ISSUE THREAD

**Issue by codypop1** [Delcos/Hentai-Diffusion#21]
I am getting an error saying it cant find the command "git" and asking if i have it in my path does anyone know how to fix this?

**Comment by Delcos** [comment]
> I am getting an error saying it cant find the command "git" and asking if i have it in my path does anyone know how to fix this?

If you are on windows google "download git for windows" if you're using anaconda terminal or on Linux type in "pip install git" or "sudo apt-get install git"

**Comment by codypop1** [comment]
thanks for the help i appreciate it
