### ISSUE TITLE
Image not generating/stuck

### ISSUE THREAD

**Issue by captainjaina** [Delcos/Hentai-Diffusion#22]
So I finished setting everything up and now that I put a prompt in ('1girl, anime,' is included) it starts but gets stuck at almost no progress and I was wondering if it's supposed to take a while or something, because it just seems to be stuck.
![obraz_2022-12-22_211707777](https://user-images.githubusercontent.com/31486295/209218822-f414c444-221f-4325-9b05-31ce93d3fb7b.png)

Edit: It's been 3 hours and there is still no progress

**Comment by Raph404** [comment]
The first run can take a little while, is there any message in the console?

**Comment by captainjaina** [comment]
> The first run can take a little while, is there any message in the console?

If you are refering to the CMD where you get the IP then no.

**Comment by captainjaina** [comment]
> The first run can take a little while, is there any message in the console?

Welp it has been almost 3 hours now and it's still stuck, do you have any ideas what might be causing that and/or how to fix it by any chance?
