### ISSUE TITLE
Guide for mastering the prompt

### ISSUE THREAD

**Issue by Vok42** [Delcos/Hentai-Diffusion#34]
Hello,

I would like to ask if you can suggest material on how to do advanced prompts?

I'm probably blind, but I can't find any material on how much effect: "()", "{}", ":number" has on the prompt.

For example, you recommended to do a "Sanity Test" in which you used advanced parameters.

If I play with the parameters, I see the difference in them, but I do not understand the technical component behind them.

If I break down my question into points:
1) I don't understand how much the result is multiplied when using "()"
2) I don't know what is the difference between "()" and "{}"
3) If you give a weight to a parameter, how much does it affect? For example "forest" and "(forest:1)" are parameters of the same weight? How will the values ​​above (:1.5) and below(0.5) be interpreted.

Maybe prompt can do a lot more things that I don't know about. I would not like to waste your time and explain to me how it works. If you can give a direction to an article/book that describes such details - I would be grateful to you.

I have one question for your model:
Do you have a library of words that were used to train the model? I understand that you used materials from "34" and "Gelbooru" and most of the tags will do, but what to do with little-known tags or non-obvious moments?
For example:
- Сan I be sure that character X or tag Y is in your model. Can I find out without testing it on the prompt?
- I would not know that you can use tags such as "masterpiece" or "best quality" in the prompt.

How should I know what prompt can accept without trying to interpret my words which the model may not understand?

I apologize in advance if there are any very obvious points here. II'm still new at work with "stable diffusion" and his branches

I have already worked with your model. In some places I am shocked by how well hands, details, objects are drawn. You have done an excellent job. I will look forward to your updates :)

**Comment by gnusenpai** [comment]
Did you find an answer for these?
