### ISSUE TITLE
can't find "lauch( )"

### ISSUE THREAD

**Issue by draconinjari** [Delcos/Hentai-Diffusion#38]
I want to turn on sharing but I can't find the file or line of code launch( ) to set share=true. I want to be able to run the UI on my phone basically while my computer does the processing.

**Comment by Kuroseji** [comment]
Not sure what client you are using but for Automatc1111 I think you want webui-user.bat. I think you can add --share to set COMMANDLINE_ARGS=
for example my webui-user looks like this.
> set PYTHON=
> set GIT=
> set VENV_DIR=
> set COMMANDLINE_ARGS= --listen
> git pull
> call webui.bat
I use listen instead of share because I only want to do generations from devices on my home network.

**Comment by draconinjari** [comment]
In the command shell right before giving the local IP it mentions making it public by adding share=true to launch( ). I'm on windows, but I'll try that and see if it will work. I wanna show this thing off to friends without needing to send them the results or be home basically.

**Comment by draconinjari** [comment]
Yup, worked!! Thx!!
