### ISSUE TITLE
--Suggestion-- Certain parts are inaccurately drawn, possible to train AI to draw them better?

### ISSUE THREAD

**Issue by linklight2** [Delcos/Hentai-Diffusion#9]
Oftentimes bodily parts are drawn incorrectly by the AI when the prompt is done nsfw. 

- Feet often have multiple heels and almost never have 5 toes 
- The body is often contorted ( like the upper body is drawn laying on their back but the butt is depicted as if they were on their hands and knees )
- If not specified by the prompt, nipples are usually not drawn at all
- Breasts if held by some sort of string will have 2 sets of nipples, one above the string and one below
- The anus is almost never correctly drawn ( usually just a red hole with no seam if it is even present )
- Arms often consist of only the shoulder and disappear into the body or clothing. Even when drawn, they sometimes turn into other anatomy, like breasts or legs
- Limbs often bend backwards or sideways

In addition, it is quite difficult to get the Ai to draw a dick correctly either. Even after being very literal and pushy with the prompt to even get one drawn in order to show the deed, the 'dick' usually ends up not being human at all. They come in all shapes and colors, oftentimes very thin and white, red like an animal's, or just made up of whatever was randomly in the environment. As for getting the Ai to depict services with said anatomy such as hotdogs, titjobs, footjobs, handjobs, etc, forget it, when it is drawn in, it always goes in the mouth, ass, or pussy.

Overall, the AI works great for depicting only 1 girl in various levels states of nudity. Once sex of any kind is introduced however, it quickly fails to preform properly. That would be my biggest suggestion on a direction to work towards for the moniker, 'Hentai Diffusion'

PS - something was misspelled on the readme.
Readme: Dispite the name there is no adult content on this page --> Despite the name there is no adult content on this page

**Comment by Delcos** [comment]
the next release (soon) is gonna be way better. here's a sneak peek.
![00051-3567457-best quality, {{{nsfw}}}, {{{masterpiece}}}, 1girl, monika _(doki doki literature club_, (breasts_0 984), (brown hair_0 989), (c - Copy](https://user-images.githubusercontent.com/28798918/204962234-a5263d85-2030-4801-889e-a5a30211f982.png)

**Comment by misu200** [comment]
> the next release (soon) is gonna be way better. here's a sneak peek. ![00051-3567457-best quality, {{{nsfw}}}, {{{masterpiece}}}, 1girl, monika (doki doki literature club, (breasts_0 984), (brown hair_0 989), (c - Copy](https://user-images.githubusercontent.com/28798918/204962234-a5263d85-2030-4801-889e-a5a30211f982.png)

Could you please share the text used for generating the above picture?
